#include "vulkan_wrapper.h"
#include "core/my_c_runtime.h"

// VMA implementation only specified in this one file.
#define VMA_IMPLEMENTATION
#include "vk_mem_alloc.h"

#define MY_VK_RESULT_LIST(X) \
    X(VK_SUCCESS) \
    X(VK_NOT_READY) \
    X(VK_TIMEOUT) \
    X(VK_EVENT_SET) \
    X(VK_EVENT_RESET) \
    X(VK_INCOMPLETE) \
    X(VK_ERROR_OUT_OF_HOST_MEMORY) \
    X(VK_ERROR_OUT_OF_DEVICE_MEMORY) \
    X(VK_ERROR_INITIALIZATION_FAILED) \
    X(VK_ERROR_DEVICE_LOST) \
    X(VK_ERROR_MEMORY_MAP_FAILED) \
    X(VK_ERROR_LAYER_NOT_PRESENT) \
    X(VK_ERROR_EXTENSION_NOT_PRESENT) \
    X(VK_ERROR_FEATURE_NOT_PRESENT) \
    X(VK_ERROR_INCOMPATIBLE_DRIVER) \
    X(VK_ERROR_TOO_MANY_OBJECTS) \
    X(VK_ERROR_FORMAT_NOT_SUPPORTED) \
    X(VK_ERROR_FRAGMENTED_POOL) \
    X(VK_ERROR_UNKNOWN) \
    X(VK_ERROR_OUT_OF_POOL_MEMORY) \
    X(VK_ERROR_INVALID_EXTERNAL_HANDLE) \
    X(VK_ERROR_FRAGMENTATION) \
    X(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS) \
    X(VK_PIPELINE_COMPILE_REQUIRED) \
    X(VK_ERROR_NOT_PERMITTED) \
    X(VK_ERROR_SURFACE_LOST_KHR) \
    X(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR) \
    X(VK_SUBOPTIMAL_KHR) \
    X(VK_ERROR_OUT_OF_DATE_KHR) \
    X(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR) \
    X(VK_ERROR_INVALID_SHADER_NV) \
    X(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT) \
    X(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT) \
    X(VK_THREAD_IDLE_KHR) \
    X(VK_THREAD_DONE_KHR) \
    X(VK_OPERATION_DEFERRED_KHR) \
    X(VK_OPERATION_NOT_DEFERRED_KHR) \
    X(VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR) \
    X(VK_ERROR_COMPRESSION_EXHAUSTED_EXT) \
    X(VK_INCOMPATIBLE_SHADER_BINARY_EXT) \
    X(VK_PIPELINE_BINARY_MISSING_KHR) \
    X(VK_ERROR_NOT_ENOUGH_SPACE_KHR) \
    X(VK_ERROR_VALIDATION_FAILED_EXT) \
    X(VK_ERROR_OUT_OF_POOL_MEMORY_KHR) \
    X(VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR) \
    X(VK_ERROR_FRAGMENTATION_EXT) \
    X(VK_ERROR_NOT_PERMITTED_EXT) \
    X(VK_ERROR_NOT_PERMITTED_KHR) \
    X(VK_ERROR_INVALID_DEVICE_ADDRESS_EXT) \
    X(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR) \
    X(VK_PIPELINE_COMPILE_REQUIRED_EXT) \
    X(VK_ERROR_PIPELINE_COMPILE_REQUIRED_EXT)

#define MY_VK_QUEUE_FLAG_BITS_LIST(X) \
    X(VK_QUEUE_GRAPHICS_BIT) \
    X(VK_QUEUE_COMPUTE_BIT) \
    X(VK_QUEUE_TRANSFER_BIT) \
    X(VK_QUEUE_SPARSE_BINDING_BIT) \
    X(VK_QUEUE_PROTECTED_BIT) \
    X(VK_QUEUE_VIDEO_DECODE_BIT_KHR) \
    X(VK_QUEUE_VIDEO_ENCODE_BIT_KHR) \
    X(VK_QUEUE_OPTICAL_FLOW_BIT_NV)

#define MY_VK_MEMORY_HEAP_FLAG_BITS_LIST(X) \
    X(VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) \
    X(VK_MEMORY_HEAP_MULTI_INSTANCE_BIT) \
    X(VK_MEMORY_HEAP_TILE_MEMORY_BIT_QCOM) \
    X(VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR)

#define MY_VK_MEMORY_PROPERTY_FLAG_BITS_LIST(X) \
    X(VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT) \
    X(VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) \
    X(VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) \
    X(VK_MEMORY_PROPERTY_HOST_CACHED_BIT) \
    X(VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT) \
    X(VK_MEMORY_PROPERTY_PROTECTED_BIT) \
    X(VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD) \
    X(VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD) \
    X(VK_MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV)


const char*
vklayer_result_to_string(VkResult result)
{
    // Can't use switch statement since some enum values are duplicated for extensions
    #define MYCASE(name) if (result == name) return #name;
    MY_VK_RESULT_LIST(MYCASE)
    #undef MYCASE
    return "Unknown VkResult Value (the list of values was last updated for vulkan 1.4)\n";
}

void
vklayer_print_queueflagbits(VkQueueFlagBits flags)
{
    #define MYCASE(name) if (flags & name) { printf(#name" "); }
    MY_VK_QUEUE_FLAG_BITS_LIST(MYCASE)
    #undef MYCASE
    printf("\n");
}

void
vklayer_print_memoryheapflagbits(VkMemoryHeapFlags flags)
{
    #define MYCASE(name) if (flags & name) { printf(#name" "); }
    MY_VK_MEMORY_HEAP_FLAG_BITS_LIST(MYCASE)
    #undef MYCASE
    printf("\n");
}

void
vklayer_print_memorypropertyflagbits(VkMemoryPropertyFlags flags)
{
    #define MYCASE(name) if (flags & name) { printf(#name" "); }
    MY_VK_MEMORY_PROPERTY_FLAG_BITS_LIST(MYCASE)
    #undef MYCASE
    printf("\n");
}

